#!/bin/bash

HOME=$OPENSHIFT_REPO_DIR
cd $OPENSHIFT_REPO_DIR

# Cache npm and bower components on main gear
if [ "$OPENSHIFT_GEAR_UUID" == "$OPENSHIFT_APP_UUID" ]; then
  mkdir -p "$OPENSHIFT_DATA_DIR"node_modules
  mkdir -p "$OPENSHIFT_DATA_DIR"bower_components

  ln -s "$OPENSHIFT_DATA_DIR"node_modules node_modules
  ln -s "$OPENSHIFT_DATA_DIR"bower_components bower_components
fi

npm install --loglevel error
npm prune

# bower install -q
